"use client";

import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { KeyRound, LoaderCircle, Pencil, Search, ShieldCheck, UserRoundPlus, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { inviteWorkspaceUser, updateUserAccess } from "@/app/actions/access-control";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";

export type AccessUser={id:string;employeeNumber:string;firstName:string;lastName:string;email:string;jobTitle:string;location:string|null;employmentStatus:"active"|"on_leave"|"terminated";isPayrollEmployee:boolean;isSystemOwner:boolean;roles:string[];departmentIds:string[];updatedAt:string};
export type AccessDepartment={id:string;name:string;code:string};
export type AccessSnapshot={users:AccessUser[];departments:AccessDepartment[];availableRoles:string[]};
const roleHelp:Record<string,string>={super_admin:"Full configuration and access management",hr_admin:"People, attendance, leave, compensation, benefits and claims",payroll_manager:"Attendance and payroll calculation",hr_manager:"Compensation, leave and claims",manager:"Read assigned departments",employee:"Read permitted personal records"};
const pretty=(value:string)=>value.replaceAll("_"," ").replace(/^./,letter=>letter.toUpperCase());

export function AccessControl({data,invitationsEnabled}:{data:AccessSnapshot;invitationsEnabled:boolean}){
  const router=useRouter();const [busy,startTransition]=useTransition();const [search,setSearch]=useState("");const [editing,setEditing]=useState<AccessUser|null>(null);const [invite,setInvite]=useState(false);
  const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return data.users.filter(user=>!q||`${user.firstName} ${user.lastName} ${user.email} ${user.employeeNumber} ${user.roles.join(" ")}`.toLowerCase().includes(q));},[data.users,search]);
  return <div className="mx-auto max-w-6xl"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-indigo-600">Settings / Security</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] text-slate-950">Access control</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Invite users and enforce least-privilege roles, authentication status, payroll eligibility, and manager department scope. Terminated accounts are denied by PostgreSQL immediately and banned in Supabase Authentication.</p></div><Button onClick={()=>setInvite(true)}><UserRoundPlus/>Invite user</Button></div>
    <nav className="mt-6 flex gap-2 border-b pb-3"><Link href="/settings/profile" className="rounded-lg px-4 py-2 text-sm font-medium text-slate-500 hover:bg-slate-50">Profile & security</Link><span className="rounded-lg bg-indigo-50 px-4 py-2 text-sm font-medium text-indigo-700">Access control</span></nav>
    <section className="mt-6 grid gap-3 sm:grid-cols-3">{[["Workspace users",data.users.length,UsersRound],["Active accounts",data.users.filter(x=>x.employmentStatus==="active").length,ShieldCheck],["Super administrators",data.users.filter(x=>x.roles.includes("super_admin")).length,KeyRound]].map(([label,value,Icon])=>{const I=Icon as typeof UsersRound;return <div key={String(label)} className="rounded-xl border bg-white p-4"><I className="size-4 text-indigo-600"/><p className="mt-3 text-2xl font-semibold">{String(value)}</p><p className="text-xs text-slate-500">{String(label)}</p></div>})}</section>
    <section className="mt-6 overflow-hidden rounded-xl border bg-white"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-sm font-semibold text-slate-900">Users and permissions</h2><p className="mt-1 text-xs text-slate-500">Every change is enforced in PostgreSQL and recorded in the audit log.</p></div><div className="relative w-full sm:w-72"><Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search users or roles…"/></div></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs text-slate-500"><tr>{["User","Roles","Status","Payroll employee","Department scope",""].map(x=><th key={x} className="px-4 py-3 font-medium">{x}</th>)}</tr></thead><tbody>{filtered.map(user=><tr key={user.id} className="border-t"><td className="px-4 py-4"><p className="font-medium text-slate-900">{user.firstName} {user.lastName}{user.isSystemOwner&&<span className="ml-2 rounded bg-indigo-50 px-1.5 py-0.5 text-[10px] text-indigo-700">Owner</span>}</p><p className="mt-1 text-xs text-slate-500">{user.email} · {user.employeeNumber}</p></td><td className="px-4"><div className="flex max-w-xs flex-wrap gap-1">{user.roles.map(role=><span key={role} className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-medium">{pretty(role)}</span>)}</div></td><td className="px-4"><span className={`rounded-full px-2 py-1 text-xs font-medium ${user.employmentStatus==="active"?"bg-emerald-50 text-emerald-700":"bg-amber-50 text-amber-700"}`}>{pretty(user.employmentStatus)}</span></td><td className="px-4">{user.isPayrollEmployee?"Yes":"No"}</td><td className="px-4 text-xs text-slate-500">{user.departmentIds.length?`${user.departmentIds.length} assigned`:"—"}</td><td className="px-4"><Button variant="ghost" size="icon" aria-label={`Edit access for ${user.firstName} ${user.lastName}`} onClick={()=>setEditing(user)}><Pencil/></Button></td></tr>)}</tbody></table>{!filtered.length&&<p className="p-10 text-center text-sm text-slate-500">No users match this search.</p>}</div></section>
    {editing&&<AccessEditor user={editing} departments={data.departments} roleOptions={data.availableRoles} busy={busy} close={()=>setEditing(null)} save={(values)=>startTransition(async()=>{const result=await updateUserAccess(values);if(!result.ok){toast.error("Access update failed",{description:`${editing.firstName} ${editing.lastName} was not changed. ${result.message}`});return;}toast.success("User access updated",{description:`Roles, account status, payroll eligibility, and department scope for ${editing.firstName} ${editing.lastName} were saved and audited.`});setEditing(null);router.refresh();})}/>} 
    {invite&&<InviteEditor departments={data.departments} roleOptions={data.availableRoles} enabled={invitationsEnabled} busy={busy} close={()=>setInvite(false)} save={(values)=>startTransition(async()=>{const result=await inviteWorkspaceUser(values);if(!result.ok){toast.error("Invitation failed",{description:result.message});return;}toast.success("Workspace invitation created",{description:`${result.message} Their profile and initial role were saved after Supabase accepted the invitation.`});setInvite(false);router.refresh();})}/>} 
  </div>;
}

function AccessEditor({user,departments,roleOptions,busy,close,save}:{user:AccessUser;departments:AccessDepartment[];roleOptions:string[];busy:boolean;close:()=>void;save:(value:unknown)=>void}){
  const [roles,setRoles]=useState(user.roles);const [departmentIds,setDepartmentIds]=useState(user.departmentIds);const [employmentStatus,setStatus]=useState(user.employmentStatus);const [isPayrollEmployee,setPayroll]=useState(user.isPayrollEmployee);const owner=user.isSystemOwner;
  const toggle=(list:string[],value:string,set:(v:string[])=>void)=>set(list.includes(value)?list.filter(x=>x!==value):[...list,value]);
  return <Dialog open onOpenChange={open=>{if(!open&&!busy)close()}}><DialogContent className="max-w-2xl"><DialogTitle>Access for {user.firstName} {user.lastName}</DialogTitle><DialogDescription>Permissions are applied atomically. The protected owner cannot be deactivated, placed on payroll, or stripped of super-admin access.</DialogDescription><form className="mt-5 space-y-5" onSubmit={e=>{e.preventDefault();save({userId:user.id,roles,departmentIds,isPayrollEmployee,employmentStatus})}}><fieldset disabled={busy||owner} className="space-y-5"><div><p className="text-sm font-medium text-slate-800">Roles</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{roleOptions.map(role=><label key={role} className="flex gap-3 rounded-lg border p-3"><input type="checkbox" className="mt-1 size-4 accent-indigo-600" checked={roles.includes(role)} onChange={()=>toggle(roles,role,setRoles)}/><span><span className="block text-sm font-medium">{pretty(role)}</span><span className="text-xs leading-5 text-slate-500">{roleHelp[role]}</span></span></label>)}</div></div><div className="grid gap-4 sm:grid-cols-2"><label><span className="text-sm font-medium text-slate-700">Account status</span><select className="mt-1.5 h-10 w-full rounded-lg border bg-white px-3 text-sm" value={employmentStatus} onChange={e=>setStatus(e.target.value as AccessUser['employmentStatus'])}>{["active","on_leave","terminated"].map(x=><option key={x} value={x}>{pretty(x)}</option>)}</select></label><label className="flex items-center gap-3 rounded-lg border p-3"><input type="checkbox" checked={isPayrollEmployee} onChange={e=>setPayroll(e.target.checked)} className="size-4 accent-indigo-600"/><span><span className="block text-sm font-medium">Payroll employee</span><span className="text-xs text-slate-500">Can receive attendance, salary and payslips</span></span></label></div>{roles.includes("manager")&&<div><p className="text-sm font-medium text-slate-800">Manager department scope</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{departments.map(department=><label key={department.id} className="flex items-center gap-2 rounded-lg border p-3 text-sm"><input type="checkbox" checked={departmentIds.includes(department.id)} onChange={()=>toggle(departmentIds,department.id,setDepartmentIds)} className="size-4 accent-indigo-600"/>{department.name} <span className="text-xs text-slate-400">{department.code}</span></label>)}</div></div>}</fieldset>{owner&&<p className="rounded-lg bg-indigo-50 p-3 text-sm text-indigo-800">System-owner access is locked by the database.</p>}<div className="flex justify-end gap-2 border-t pt-4"><Button type="button" variant="secondary" onClick={close} disabled={busy}>Cancel</Button><Button disabled={busy||owner||roles.length===0}>{busy&&<LoaderCircle className="animate-spin"/>}Save access</Button></div></form></DialogContent></Dialog>;
}

function InviteEditor({departments,roleOptions,enabled,busy,close,save}:{departments:AccessDepartment[];roleOptions:string[];enabled:boolean;busy:boolean;close:()=>void;save:(value:unknown)=>void}){
  const [value,setValue]=useState({employeeNumber:"",firstName:"",lastName:"",email:"",jobTitle:"",departmentId:"",role:"employee"});const set=(key:string,next:string)=>setValue(current=>({...current,[key]:next}));
  return <Dialog open onOpenChange={open=>{if(!open&&!busy)close()}}><DialogContent className="max-w-2xl"><DialogTitle>Invite a workspace user</DialogTitle><DialogDescription>Supabase sends the account invitation. The profile and initial role are created only when the invitation succeeds.</DialogDescription>{!enabled&&<p className="mt-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-900">Add the server-only SUPABASE_SERVICE_ROLE_KEY to enable invitations.</p>}<form className="mt-5" onSubmit={e=>{e.preventDefault();save({...value,departmentId:value.departmentId||null})}}><fieldset disabled={busy||!enabled} className="grid gap-4 sm:grid-cols-2">{([['firstName','First name','text'],['lastName','Last name','text'],['email','Work email','email'],['employeeNumber','Employee number','text'],['jobTitle','Job title','text']] as const).map(([key,label,type])=><label key={key} className={key==="jobTitle"?"sm:col-span-2":""}><span className="text-sm font-medium text-slate-700">{label}</span><Input required type={type} className="mt-1.5" value={value[key]} onChange={e=>set(key,e.target.value)}/></label>)}<label><span className="text-sm font-medium text-slate-700">Initial role</span><select className="mt-1.5 h-10 w-full rounded-lg border bg-white px-3 text-sm" value={value.role} onChange={e=>set("role",e.target.value)}>{roleOptions.map(role=><option key={role} value={role}>{pretty(role)}</option>)}</select></label><label><span className="text-sm font-medium text-slate-700">Department</span><select className="mt-1.5 h-10 w-full rounded-lg border bg-white px-3 text-sm" value={value.departmentId} onChange={e=>set("departmentId",e.target.value)}><option value="">Unassigned</option>{departments.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label></fieldset><div className="mt-6 flex justify-end gap-2 border-t pt-4"><Button type="button" variant="secondary" onClick={close} disabled={busy}>Cancel</Button><Button disabled={busy||!enabled}>{busy&&<LoaderCircle className="animate-spin"/>}Send invitation</Button></div></form></DialogContent></Dialog>;
}
