"use client";

import { useState, useTransition } from "react";
import Link from "next/link";
import { CheckCircle2, KeyRound, LoaderCircle, ShieldCheck, Smartphone, UserRound, UsersRound } from "lucide-react";
import { toast } from "sonner";
import { updateAccountPassword, updateAccountProfile } from "@/app/actions/account";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export type AccountProfile = { id:string; employeeNumber:string; firstName:string; lastName:string; email:string; jobTitle:string; location:string|null; isSystemOwner:boolean; isPayrollEmployee:boolean; roles:string[] };

export function AccountSettings({profile,mfaFactorCount}:{profile:AccountProfile;mfaFactorCount:number}) {
  const [busy,startTransition]=useTransition();
  const [values,setValues]=useState({firstName:profile.firstName,lastName:profile.lastName,jobTitle:profile.jobTitle,location:profile.location??""});
  const [fields,setFields]=useState<Record<string,string[]>>({});
  const [passwords,setPasswords]=useState({password:"",confirmPassword:""});
  const [passwordFields,setPasswordFields]=useState<Record<string,string[]>>({});
  const initials=`${values.firstName[0]??""}${values.lastName[0]??""}`.toUpperCase();

  function saveProfile(event:React.FormEvent) { event.preventDefault(); startTransition(async()=>{const result=await updateAccountProfile(values);if(!result.ok){setFields(result.fields??{});toast.error("Profile update failed",{description:result.message});return;}setFields({});toast.success("Administrator profile updated",{description:`${values.firstName} ${values.lastName}'s name, title, and location were saved to the audited profile.`});}); }
  function savePassword(event:React.FormEvent) { event.preventDefault(); startTransition(async()=>{const result=await updateAccountPassword(passwords);if(!result.ok){setPasswordFields(result.fields??{});toast.error("Password change failed",{description:result.message});return;}setPasswordFields({});setPasswords({password:"",confirmPassword:""});toast.success("Password changed securely",{description:"The new password is active for the next sign-in. Your MFA protection remains enabled."});}); }

  return <div className="mx-auto max-w-5xl">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-indigo-600">Account settings</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] text-slate-950">Profile & security</h1><p className="mt-2 text-sm text-slate-500">Manage the identity used for administration, approvals, and audit history.</p></div><div className="flex items-center gap-3 rounded-xl border bg-white px-4 py-3"><span className="grid size-11 place-items-center rounded-full bg-indigo-600 font-semibold text-white">{initials||"A"}</span><div><p className="text-sm font-semibold text-slate-900">{values.firstName} {values.lastName}</p><p className="text-xs text-slate-500">{profile.email}</p></div></div></div>
    <nav className="mt-6 flex gap-2 border-b pb-3"><span className="rounded-lg bg-indigo-50 px-4 py-2 text-sm font-medium text-indigo-700">Profile & security</span>{profile.roles.includes("super_admin")&&<Link href="/settings/access" className="inline-flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium text-slate-500 hover:bg-slate-50"><UsersRound className="size-4"/>Access control</Link>}</nav>
    {profile.isSystemOwner&&<div className="mt-6 flex gap-3 rounded-xl border border-indigo-200 bg-indigo-50 p-4"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-indigo-700"/><div><p className="text-sm font-semibold text-indigo-950">Protected system owner</p><p className="mt-1 text-sm leading-6 text-indigo-800">This identity is retained for login and audit history but excluded from employee records, attendance, payroll, benefits, and payslips.</p></div></div>}
    <div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_300px]">
      <form onSubmit={saveProfile} className="rounded-xl border bg-white p-5 sm:p-6"><div className="flex items-center gap-2"><UserRound className="size-5 text-indigo-600"/><h2 className="font-semibold text-slate-950">Personal details</h2></div><div className="mt-5 grid gap-4 sm:grid-cols-2">{([['firstName','First name'],['lastName','Last name'],['jobTitle','Job title'],['location','Location']] as const).map(([key,label])=><label key={key}><span className="text-sm font-medium text-slate-700">{label}</span><Input className="mt-1.5" value={values[key]} onChange={(e)=>setValues(current=>({...current,[key]:e.target.value}))} aria-invalid={Boolean(fields[key])}/>{fields[key]&&<span className="mt-1 block text-xs text-red-600">{fields[key].join(" ")}</span>}</label>)}</div><div className="mt-5 grid gap-4 border-t pt-5 sm:grid-cols-2"><label><span className="text-sm font-medium text-slate-700">Work email</span><Input className="mt-1.5" value={profile.email} disabled/><span className="mt-1 block text-xs text-slate-500">Managed by Supabase Authentication.</span></label><label><span className="text-sm font-medium text-slate-700">Administrator ID</span><Input className="mt-1.5" value={profile.employeeNumber} disabled/><span className="mt-1 block text-xs text-slate-500">Identity reference—not a payroll employee number.</span></label></div><Button className="mt-6" disabled={busy}>{busy&&<LoaderCircle className="animate-spin"/>}Save profile</Button></form>
      <aside className="space-y-6"><section className="rounded-xl border bg-white p-5"><h2 className="text-sm font-semibold text-slate-950">Access</h2><div className="mt-4 flex flex-wrap gap-2">{profile.roles.map(role=><span key={role} className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-medium text-indigo-700">{role.replaceAll('_',' ')}</span>)}</div><div className="mt-4 flex items-start gap-2 text-xs leading-5 text-emerald-700"><CheckCircle2 className="mt-0.5 size-4 shrink-0"/>Account active and protected</div></section>
      <section className="rounded-xl border bg-white p-5"><div className="flex items-center gap-2"><Smartphone className="size-4 text-indigo-600"/><h2 className="text-sm font-semibold text-slate-950">Multi-factor authentication</h2></div><p className="mt-3 text-xs leading-5 text-slate-500">{mfaFactorCount?`${mfaFactorCount} verified authenticator${mfaFactorCount===1?'':'s'} protect this account.`:"Add an authenticator app to protect payroll and employee data."}</p><Button asChild variant="secondary" className="mt-4 w-full"><Link href="/mfa/setup">{mfaFactorCount?"Manage authenticators":"Set up MFA"}</Link></Button></section>
      <form onSubmit={savePassword} className="rounded-xl border bg-white p-5"><div className="flex items-center gap-2"><KeyRound className="size-4 text-indigo-600"/><h2 className="text-sm font-semibold text-slate-950">Change password</h2></div><div className="mt-4 space-y-3"><label><span className="text-xs font-medium text-slate-700">New password</span><Input className="mt-1.5" type="password" autoComplete="new-password" value={passwords.password} onChange={(e)=>setPasswords(v=>({...v,password:e.target.value}))}/>{passwordFields.password&&<span className="mt-1 block text-xs text-red-600">{passwordFields.password.join(" ")}</span>}</label><label><span className="text-xs font-medium text-slate-700">Confirm password</span><Input className="mt-1.5" type="password" autoComplete="new-password" value={passwords.confirmPassword} onChange={(e)=>setPasswords(v=>({...v,confirmPassword:e.target.value}))}/>{passwordFields.confirmPassword&&<span className="mt-1 block text-xs text-red-600">{passwordFields.confirmPassword.join(" ")}</span>}</label></div><p className="mt-3 text-xs leading-5 text-slate-500">Use at least 12 characters with upper/lowercase letters and a number.</p><Button className="mt-4 w-full" variant="secondary" disabled={busy}>Update password</Button></form></aside>
    </div>
  </div>;
}
