"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle2, Plus, Save, Settings2 } from "lucide-react";
import { toast } from "sonner";
import { savePayrollPolicy, type PayrollPolicyInput, type PayrollPolicyRow } from "@/app/actions/payroll-policy";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

const defaults: PayrollPolicyInput = { name: "Company payroll policy", version: "COMPANY-v1", effectiveFrom: new Date().toISOString().slice(0,10), effectiveTo: "", status: "draft", workdaysPerMonth: 22, hoursPerDay: 8, ordinaryOtMultiplier: 1.25, restDayOtMultiplier: 1.69, specialDayOtMultiplier: 1.69, regularHolidayOtMultiplier: 2.6, doubleHolidayOtMultiplier: 3.9, nightDifferentialRate: .1, contributionAllocation: "split_evenly", comparisonTolerance: 1, sssEmployeeRate:.05, sssEmployerRate:.10, sssMinMsc:5000, sssMaxMsc:35000, philhealthRate:.05, philhealthFloor:10000, philhealthCeiling:100000, pagibigLowRate:.01, pagibigHighRate:.02, pagibigEmployerRate:.02, pagibigRateThreshold:1500, pagibigSalaryCap:10000 };
const fromRow = (row: PayrollPolicyRow): PayrollPolicyInput => ({ id: row.id, name: row.name, version: row.version, effectiveFrom: row.effective_from, effectiveTo: row.effective_to ?? "", status: row.status, workdaysPerMonth: Number(row.workdays_per_month), hoursPerDay: Number(row.hours_per_day), ordinaryOtMultiplier: Number(row.ordinary_ot_multiplier), restDayOtMultiplier: Number(row.rest_day_ot_multiplier), specialDayOtMultiplier: Number(row.special_day_ot_multiplier), regularHolidayOtMultiplier: Number(row.regular_holiday_ot_multiplier), doubleHolidayOtMultiplier: Number(row.double_holiday_ot_multiplier), nightDifferentialRate: Number(row.night_differential_rate), contributionAllocation: row.contribution_allocation, comparisonTolerance: Number(row.comparison_tolerance), sssEmployeeRate:Number(row.sss_employee_rate), sssEmployerRate:Number(row.sss_employer_rate), sssMinMsc:Number(row.sss_min_msc), sssMaxMsc:Number(row.sss_max_msc), philhealthRate:Number(row.philhealth_rate), philhealthFloor:Number(row.philhealth_floor), philhealthCeiling:Number(row.philhealth_ceiling), pagibigLowRate:Number(row.pagibig_low_rate), pagibigHighRate:Number(row.pagibig_high_rate), pagibigEmployerRate:Number(row.pagibig_employer_rate), pagibigRateThreshold:Number(row.pagibig_rate_threshold), pagibigSalaryCap:Number(row.pagibig_salary_cap) });

export function PayrollPolicyManager({ policies, canEdit }: { policies: PayrollPolicyRow[]; canEdit: boolean }) {
  const router = useRouter();
  const [selected, setSelected] = useState<PayrollPolicyInput>(() => policies[0] ? fromRow(policies[0]) : defaults);
  const [busy, startTransition] = useTransition();
  const numberFields: Array<[keyof PayrollPolicyInput,string,string]> = [["workdaysPerMonth","Workdays per month","Used to derive daily and hourly rates"],["hoursPerDay","Hours per day","Used for hourly and absence calculations"],["ordinaryOtMultiplier","Ordinary-day OT","Example: 1.25"],["restDayOtMultiplier","Rest-day OT","Example: 1.69"],["specialDayOtMultiplier","Special-day OT","Example: 1.69"],["regularHolidayOtMultiplier","Regular-holiday OT","Example: 2.60"],["doubleHolidayOtMultiplier","Double-holiday OT","Example: 3.90"],["nightDifferentialRate","Night differential","Decimal rate, for example 0.10"],["comparisonTolerance","Payslip tolerance","Allowed peso difference in validation cases"],["sssEmployeeRate","SSS employee rate","Decimal rate"],["sssEmployerRate","SSS employer rate","Decimal rate"],["sssMinMsc","SSS minimum MSC","Monthly salary credit floor"],["sssMaxMsc","SSS maximum MSC","Monthly salary credit ceiling"],["philhealthRate","PhilHealth total rate","Split equally between employee and employer"],["philhealthFloor","PhilHealth salary floor","Monthly basic salary floor"],["philhealthCeiling","PhilHealth salary ceiling","Monthly basic salary ceiling"],["pagibigLowRate","Pag-IBIG low employee rate","Rate at or below threshold"],["pagibigHighRate","Pag-IBIG high employee rate","Rate above threshold"],["pagibigEmployerRate","Pag-IBIG employer rate","Employer counterpart rate"],["pagibigRateThreshold","Pag-IBIG rate threshold","Monthly compensation threshold"],["pagibigSalaryCap","Pag-IBIG salary cap","Maximum compensation basis"]];
  const set = (key: keyof PayrollPolicyInput, value: string | number) => setSelected((current) => ({ ...current, [key]: value }));
  const save = () => startTransition(async () => { const result = await savePayrollPolicy(selected); if (!result.ok) { toast.error("Policy not saved", { description: `${selected.name} was not changed. ${result.message}` }); return; } toast.success(`Payroll policy ${selected.id ? "updated" : "created"}`, { description: `${selected.name} (${selected.version}) was saved as ${selected.status}. ${selected.status === "active" ? "It is available for covered payroll periods." : "Activate it after payroll and accounting review."}` }); setSelected(fromRow(result.data)); router.refresh(); });
  return <div className="grid gap-6 xl:grid-cols-[320px_1fr]">
    <aside className="rounded-2xl border bg-white p-4"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Policy versions</p><p className="mt-1 text-xs text-slate-500">Historical runs keep their selected version.</p></div>{canEdit&&<Button size="icon" variant="secondary" onClick={()=>setSelected({...defaults,version:`COMPANY-v${policies.length+1}`})} aria-label="New policy"><Plus/></Button>}</div><div className="mt-4 space-y-2">{policies.map((policy)=><button key={policy.id} onClick={()=>setSelected(fromRow(policy))} className={`w-full rounded-xl border p-3 text-left ${selected.id===policy.id?"border-indigo-300 bg-indigo-50":"hover:bg-slate-50"}`}><span className="flex items-center justify-between gap-2 text-sm font-medium">{policy.name}{policy.status==="active"&&<CheckCircle2 className="size-4 text-emerald-600"/>}</span><span className="mt-1 block text-xs text-slate-500">{policy.version} · {policy.effective_from}</span></button>)}</div></aside>
    <section className="rounded-2xl border bg-white p-5 sm:p-7"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Settings2 className="size-5"/></span><div><h2 className="font-semibold">Company calculation rules</h2><p className="text-xs text-slate-500">Activate only after payroll/accounting review.</p></div></div>
      <div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-sm">Policy name<Input className="mt-1.5" value={selected.name} disabled={!canEdit||busy} onChange={e=>set("name",e.target.value)}/></label><label className="text-sm">Version<Input className="mt-1.5" value={selected.version} disabled={!canEdit||busy||Boolean(selected.id)} onChange={e=>set("version",e.target.value)}/></label><label className="text-sm">Effective from<Input type="date" className="mt-1.5" value={selected.effectiveFrom} disabled={!canEdit||busy} onChange={e=>set("effectiveFrom",e.target.value)}/></label><label className="text-sm">Effective to (optional)<Input type="date" className="mt-1.5" value={selected.effectiveTo} disabled={!canEdit||busy} onChange={e=>set("effectiveTo",e.target.value)}/></label><label className="text-sm">Status<select className="mt-1.5 h-10 w-full rounded-lg border bg-white px-3" value={selected.status} disabled={!canEdit||busy} onChange={e=>set("status",e.target.value)}><option value="draft">Draft</option><option value="active">Active</option><option value="retired">Retired</option></select></label><label className="text-sm">Statutory deduction cutoff<select className="mt-1.5 h-10 w-full rounded-lg border bg-white px-3" value={selected.contributionAllocation} disabled={!canEdit||busy} onChange={e=>set("contributionAllocation",e.target.value)}><option value="split_evenly">Split evenly</option><option value="first_cutoff">First cutoff</option><option value="second_cutoff">Second cutoff</option></select></label>{numberFields.map(([key,label,help])=><label className="text-sm" key={key}>{label}<Input type="number" min="0" step="0.001" className="mt-1.5" value={Number(selected[key])} disabled={!canEdit||busy} onChange={e=>set(key,Number(e.target.value))}/><span className="mt-1 block text-xs text-slate-400">{help}</span></label>)}</div>
      <div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900">SSS, PhilHealth, Pag-IBIG, and BIR defaults are versioned in the database. Creating a new active version is required for future statutory changes; finalized payroll keeps its original policy reference.</div>
      {canEdit?<Button className="mt-6" onClick={save} disabled={busy}><Save/>{busy?"Saving…":"Save policy"}</Button>:<p className="mt-6 text-sm text-slate-500">Only a super administrator can change policy. Payroll and HR administrators have read-only access.</p>}
    </section>
  </div>;
}
