export type Field = {
  key: string; label: string; type?: "text" | "email" | "date" | "datetime-local" | "number" | "select" | "textarea" | "checkbox";
  required?: boolean; options?: string[]; reference?: string; createOnly?: boolean; min?: number; help?: string;
};
export type EntityConfig = { title: string; singular: string; description: string; fields: Field[]; columns: string[]; roles: string[] };
const hr = ["super_admin", "hr_admin"];
const people = [...hr, "hr_manager"];
const payroll = ["super_admin", "payroll_manager"];
const employee: Field = { key: "employee_id", label: "Employee", reference: "profiles", required: true };
const money = (key: string, label: string): Field => ({ key, label, type: "number", min: 0, required: true });
const date = (key: string, label: string, required = true): Field => ({ key, label, type: "date", required });
const status = (options: string[]): Field => ({ key: "status", label: "Status", type: "select", options, required: true });

export const entities: Record<string, EntityConfig> = {
  departments: { title: "Departments", singular: "department", description: "Maintain the departments used by employee records.", roles: hr,
    fields: [{ key: "name", label: "Name", required: true }, { key: "code", label: "Code", required: true, help: "2–16 uppercase letters, numbers, underscores or hyphens." }], columns: ["name", "code"] },
  profiles: { title: "Employees", singular: "employee", description: "Maintain payroll employee details. Super administrators should invite login users and manage account status from Settings → Access control.", roles: hr,
    fields: [{ key: "id", label: "Auth user ID", required: true, createOnly: true, help: "Existing Supabase Authentication user UUID. Prefer Access control → Invite user when this person needs a login." }, { key: "employee_number", label: "Employee number", required: true }, { key: "first_name", label: "First name", required: true }, { key: "last_name", label: "Last name", required: true }, { key: "email", label: "Email", type: "email", required: true }, { key: "department_id", label: "Department", reference: "departments" }, { key: "job_title", label: "Job title", required: true }, { key: "location", label: "Location" }, date("hired_at", "Hire date", false)], columns: ["employee_number", "first_name", "last_name", "department_id", "job_title", "employment_status"] },
  attendance_records: { title: "Attendance", singular: "attendance record", description: "Maintain time records and reviewed attendance minutes. Late, undertime, absence, and overtime minutes flow into draft payroll when it is calculated.", roles: [...hr, "payroll_manager"],
    fields: [employee, { key: "external_id", label: "Source reference", required: true, help: "Unique reference, for example MANUAL-EMP001-2026-09-05." }, date("attendance_date", "Attendance date"), { key: "time_in", label: "Time in", type: "datetime-local" }, { key: "time_out", label: "Time out", type: "datetime-local" }, ...["worked", "late", "undertime", "overtime", "absence"].map((key) => money(`${key}_minutes`, `${key[0].toUpperCase()}${key.slice(1)} minutes`)), { key: "classification", label: "Classification", type: "select", options: ["on_time", "late", "absent", "overtime", "on_leave"], required: true }, { key: "approved_leave", label: "Approved leave", type: "checkbox" }], columns: ["employee_id", "attendance_date", "time_in", "time_out", "classification", "worked_minutes", "late_minutes", "overtime_minutes"] },
  leave_requests: { title: "Leave approvals", singular: "leave request", description: "Review leave requests. Approved paid weekdays are included automatically the next time a draft payroll run is calculated.", roles: people,
    fields: [employee, { key: "leave_type", label: "Leave type", type: "select", options: ["vacation", "sick", "emergency", "maternity", "paternity", "service_incentive", "other"], required: true }, date("start_date", "Start date"), date("end_date", "End date"), money("total_days", "Total days"), { key: "is_paid", label: "Paid leave", type: "checkbox" }, { key: "reason", label: "Reason", type: "textarea", required: true }, status(["draft", "submitted", "approved", "rejected", "cancelled"]), { key: "rejection_reason", label: "Rejection reason", type: "textarea" }], columns: ["employee_id", "leave_type", "start_date", "end_date", "total_days", "is_paid", "status"] },
  compensation_cycles: { title: "Compensation cycles", singular: "cycle", description: "Define review periods and budgets before adding salary proposals.", roles: people,
    fields: [{ key: "name", label: "Name", required: true }, date("starts_on", "Start date"), date("ends_on", "End date"), money("budget", "Budget"), status(["draft", "active", "closed"])], columns: ["name", "starts_on", "ends_on", "budget", "status"] },
  compensation_reviews: { title: "Salary proposals", singular: "salary proposal", description: "Create and review compensation changes. Approval creates the next effective salary record automatically; an approved bonus is included once in the next eligible payroll.", roles: people,
    fields: [employee, { key: "cycle_id", label: "Review cycle", reference: "compensation_cycles", required: true }, money("current_salary", "Current salary"), money("proposed_salary", "Proposed salary"), money("bonus", "Bonus"), { key: "justification", label: "Justification", type: "textarea", required: true }, status(["draft", "submitted", "approved", "rejected"])], columns: ["employee_id", "cycle_id", "current_salary", "proposed_salary", "increase_percentage", "status"] },
  employee_compensation_history: { title: "Salary history", singular: "salary record", description: "Store effective salary records. Avoid overlapping dates; payroll calculations are a separate workflow.", roles: people,
    fields: [employee, money("base_salary", "Base salary"), { key: "salary_frequency", label: "Frequency", type: "select", options: ["monthly", "semi_monthly", "daily", "hourly"], required: true }, date("effective_from", "Effective from"), date("effective_to", "Effective to", false)], columns: ["employee_id", "base_salary", "salary_frequency", "effective_from", "effective_to", "source"] },
  benefit_providers: { title: "Providers", singular: "provider", description: "Maintain health and benefit providers.", roles: hr,
    fields: [{ key: "name", label: "Name", required: true }, status(["active", "inactive"])], columns: ["name", "status"] },
  benefit_plans: { title: "Benefit plans", singular: "benefit plan", description: "Define plans and their employee and employer costs.", roles: hr,
    fields: [{ key: "provider_id", label: "Provider", reference: "benefit_providers", required: true }, { key: "name", label: "Name", required: true }, { key: "description", label: "Description", type: "textarea" }, { key: "benefit_type", label: "Benefit type", type: "select", options: ["HMO", "Allowance", "Insurance", "Leave", "Government"], required: true }, money("employee_cost", "Employee cost"), money("employer_cost", "Employer cost"), { key: "coverage_type", label: "Coverage", type: "select", options: ["employee_only", "employee_plus_one", "family"], required: true }, status(["active", "inactive"])], columns: ["name", "provider_id", "benefit_type", "employee_cost", "employer_cost", "status"] },
  employee_benefits: { title: "Employee benefits", singular: "employee benefit", description: "Manage enrollments and reviewed eligibility. Active eligible plan costs are applied when a matching draft payroll is calculated.", roles: hr,
    fields: [employee, { key: "plan_id", label: "Plan", reference: "benefit_plans", required: true }, { key: "membership_number", label: "Membership / reference number", required: true }, date("effective_date", "Effective date"), date("expiration_date", "Expiration date", false), { key: "eligibility", label: "Eligibility review", type: "select", options: ["pending_documents", "eligible", "not_eligible"], required: true }, status(["pending", "active", "inactive", "terminated", "expired"])], columns: ["employee_id", "plan_id", "membership_number", "eligibility", "status", "effective_date", "expiration_date"] },
  claims: { title: "Claims & reimbursements", singular: "claim", description: "Maintain claims, supporting-document links, and review status. Approved claims are included once when the next matching draft payroll is calculated.", roles: people,
    fields: [employee, { key: "claim_number", label: "Claim number", required: true }, { key: "category", label: "Category", type: "select", options: ["transportation", "meals", "medical", "travel", "office_expense", "communication", "other"], required: true }, { key: "description", label: "Description", type: "textarea", required: true }, money("amount", "Amount"), { key: "receipt_url", label: "Supporting document URL", help: "HTTPS link to a document you are authorized to review. File uploads are not provided here." }, { key: "verification_status", label: "Document review", type: "select", options: ["pending", "verified", "needs_review", "missing_document"], required: true }, status(["draft", "submitted", "under_review", "approved", "rejected"]), { key: "rejection_reason", label: "Rejection reason", type: "textarea" }], columns: ["claim_number", "employee_id", "category", "amount", "verification_status", "status"] },
  payroll_runs: { title: "Payroll runs", singular: "payroll run", description: "Create a 1st-cutoff, 2nd-cutoff, or monthly draft, then open it to calculate salaries, attendance deductions, statutory deductions, benefits, reimbursements, and payslips.", roles: payroll,
    fields: [date("period_start", "Period start"), date("period_end", "Period end"), date("pay_date", "Pay date")], columns: ["period_start", "period_end", "pay_date", "employee_count", "total_gross", "total_deductions", "total_net", "status"] },
  payroll_items: { title: "Employee payroll entries", singular: "payroll entry", description: "Calculated payroll details. Recalculate after changing attendance, salary, approved leave, benefits, or claims; bonus and other authorized deductions remain editable in a draft.", roles: payroll,
    fields: [{ key: "payroll_run_id", label: "Payroll run", reference: "payroll_runs", required: true, createOnly: true }, employee, money("bonus", "Approved bonus"), money("other_deductions", "Other authorized deductions"), status(["needs_review", "ready", "excluded"])], columns: ["employee_id", "salary_frequency", "basic_salary", "paid_leave_days", "late_minutes", "late_deduction", "overtime_minutes", "overtime", "bonus", "sss_employee", "philhealth_employee", "withholding_tax", "deductions", "gross_pay", "net_pay", "status"] },
};

export type RecordRow = { id: string; updated_at: string; [key: string]: string | number | boolean | null };
export const modules = {
  attendance: ["profiles", "attendance_records", "leave_requests", "departments"],
  compensation: ["compensation_reviews", "compensation_cycles", "employee_compensation_history"],
  benefits: ["employee_benefits", "benefit_plans", "benefit_providers"],
  claims: ["claims"], payroll: ["payroll_runs"],
} as const;

export function recordLabel(entity: string, row: RecordRow) {
  if (entity === "profiles") return `${row.employee_number} · ${row.first_name} ${row.last_name}`;
  if (entity === "payroll_runs") return `${row.period_start} – ${row.period_end} (${row.status})`;
  return String(row.name ?? row.claim_number ?? row.membership_number ?? row.id);
}
