export type Field = {
  key: string; label: string; type?: "text" | "email" | "date" | "datetime-local" | "number" | "select" | "textarea" | "checkbox";
  required?: boolean; options?: string[]; reference?: string; createOnly?: boolean; min?: number; help?: string;
};
export type EntityConfig = { title: string; singular: string; description: string; fields: Field[]; columns: string[]; roles: string[]; allowCreate?: boolean; createNotice?: string };
const hr = ["super_admin", "hr_admin"];
const people = [...hr, "hr_manager"];
const payroll = ["super_admin", "payroll_manager"];
const employee: Field = { key: "employee_id", label: "Employee", reference: "profiles", required: true };
const money = (key: string, label: string): Field => ({ key, label, type: "number", min: 0, required: true });
const date = (key: string, label: string, required = true): Field => ({ key, label, type: "date", required });
const status = (options: string[]): Field => ({ key: "status", label: "Status", type: "select", options, required: true });

export const entities: Record<string, EntityConfig> = {
  departments: { title: "Departments", singular: "department", description: "Maintain the departments used by employee records.", roles: hr,
    fields: [{ key: "name", label: "Name", required: true }, { key: "code", label: "Code", required: true, help: "2–16 uppercase letters, numbers, underscores or hyphens." }], columns: ["name", "code"] },
  profiles: { title: "Employees", singular: "employee", description: "Employee master data is owned by HR2. Synchronize HR2 to retrieve new employees; synchronized profiles appear here immediately and may be reviewed or corrected by authorized HR users.", roles: hr, allowCreate: false, createNotice: "Employees cannot be created manually in Payroll & Benefits. Use Sync with HR2 to retrieve the employee master list.",
    fields: [{ key: "id", label: "Auth user ID", required: true, createOnly: true, help: "Existing Supabase Authentication user UUID. Prefer Access control → Invite user when this person needs a login." }, { key: "employee_number", label: "Employee number", required: true }, { key: "first_name", label: "First name", required: true }, { key: "last_name", label: "Last name", required: true }, { key: "email", label: "Email", type: "email", required: true }, { key: "department_id", label: "Department", reference: "departments" }, { key: "job_title", label: "Job title", required: true }, { key: "location", label: "Location" }, date("hired_at", "Hire date", false)], columns: ["employee_number", "first_name", "last_name", "department_id", "job_title", "employment_status"] },
  attendance_records: { title: "Attendance", singular: "attendance record", description: "Maintain reviewed attendance minutes and day type. Late, absence, categorized overtime, and night minutes flow into draft payroll.", roles: [...hr, "payroll_manager"],
    fields: [employee, { key: "external_id", label: "Source reference", required: true, help: "Unique reference, for example MANUAL-EMP001-2026-09-05." }, date("attendance_date", "Attendance date"), { key: "time_in", label: "Time in", type: "datetime-local" }, { key: "time_out", label: "Time out", type: "datetime-local" }, ...["worked", "late", "undertime", "overtime", "absence", "night"].map((key) => money(`${key}_minutes`, `${key[0].toUpperCase()}${key.slice(1)} minutes`)), { key: "work_day_type", label: "Work day type", type: "select", options: ["ordinary", "rest_day", "special_non_working", "regular_holiday", "double_holiday"], required: true }, { key: "classification", label: "Classification", type: "select", options: ["on_time", "late", "absent", "overtime", "on_leave"], required: true }, { key: "approved_leave", label: "Approved leave", type: "checkbox" }], columns: ["employee_id", "attendance_date", "work_day_type", "classification", "worked_minutes", "late_minutes", "overtime_minutes", "night_minutes"] },
  leave_requests: { title: "Leave approvals", singular: "leave request", description: "Review leave requests synchronized from HR2. Approved paid weekdays are included automatically the next time a draft payroll run is calculated.", roles: people, allowCreate: false, createNotice: "Leave requests originate in HR2. Synchronize HR2 to retrieve submitted and approved leave requests; manual creation is disabled here.",
    fields: [employee, { key: "leave_type", label: "Leave type", type: "select", options: ["vacation", "sick", "emergency", "maternity", "paternity", "service_incentive", "other"], required: true }, date("start_date", "Start date"), date("end_date", "End date"), money("total_days", "Total days"), { key: "is_paid", label: "Paid leave", type: "checkbox" }, { key: "reason", label: "Reason", type: "textarea", required: true }, status(["draft", "submitted", "approved", "rejected", "cancelled"]), { key: "rejection_reason", label: "Rejection reason", type: "textarea" }], columns: ["employee_id", "leave_type", "start_date", "end_date", "total_days", "is_paid", "status"] },
  compensation_cycles: { title: "Compensation cycles", singular: "cycle", description: "Define review periods and budgets before adding salary proposals.", roles: people,
    fields: [{ key: "name", label: "Name", required: true }, date("starts_on", "Start date"), date("ends_on", "End date"), money("budget", "Budget"), status(["draft", "active", "closed"])], columns: ["name", "starts_on", "ends_on", "budget", "status"] },
  compensation_reviews: { title: "Salary proposals", singular: "salary proposal", description: "Plan the employee's proposed pay, effective date, salary adjustment and budget impact before implementation. Workflow: Pending → HR Review → Finance Review → Approved → Implemented.", roles: [...people, "payroll_manager"],
    fields: [employee, { key: "cycle_id", label: "Review cycle", reference: "compensation_cycles", required: true }, money("current_salary", "Current salary"), money("proposed_salary", "Employee should receive"), money("bonus", "One-time bonus"), date("effective_date", "Effective date"), { key: "justification", label: "Adjustment reason / justification", type: "textarea", required: true }, status(["draft", "pending", "hr_review", "finance_review", "approved", "implemented", "rejected"])], columns: ["employee_id", "cycle_id", "current_salary", "proposed_salary", "adjustment_amount", "increase_percentage", "effective_date", "within_budget", "budget_remaining_after", "status"] },
  employee_compensation_history: { title: "Salary history", singular: "salary record", description: "View previous and current salaries with their effective dates. Implemented compensation proposals create the next record automatically.", roles: people,
    fields: [employee, money("base_salary", "Base salary"), { key: "salary_frequency", label: "Frequency", type: "select", options: ["monthly", "semi_monthly", "daily", "hourly"], required: true }, date("effective_from", "Effective from"), date("effective_to", "Effective to", false)], columns: ["employee_id", "base_salary", "salary_frequency", "effective_from", "effective_to", "source"] },
  benefit_providers: { title: "Providers", singular: "provider", description: "Maintain health and benefit providers.", roles: hr,
    fields: [{ key: "name", label: "Name", required: true }, status(["active", "inactive"])], columns: ["name", "status"] },
  benefit_plans: { title: "Benefit plans", singular: "benefit plan", description: "Define plans and their employee and employer costs.", roles: hr,
    fields: [{ key: "provider_id", label: "Provider", reference: "benefit_providers", required: true }, { key: "name", label: "Name", required: true }, { key: "description", label: "Description", type: "textarea" }, { key: "benefit_type", label: "Benefit type", type: "select", options: ["HMO", "Allowance", "Insurance", "Leave", "Government"], required: true }, money("employee_cost", "Employee cost"), money("employer_cost", "Employer cost"), { key: "coverage_type", label: "Coverage", type: "select", options: ["employee_only", "employee_plus_one", "family"], required: true }, status(["active", "inactive"])], columns: ["name", "provider_id", "benefit_type", "employee_cost", "employer_cost", "status"] },
  employee_benefits: { title: "Employee benefits", singular: "employee benefit", description: "Manage enrollments and reviewed eligibility. Active eligible plan costs are applied when a matching draft payroll is calculated.", roles: hr,
    fields: [employee, { key: "plan_id", label: "Plan", reference: "benefit_plans", required: true }, { key: "membership_number", label: "Membership / reference number", required: true }, date("effective_date", "Effective date"), date("expiration_date", "Expiration date", false), { key: "eligibility", label: "Eligibility review", type: "select", options: ["pending_documents", "eligible", "not_eligible"], required: true }, status(["pending", "active", "inactive", "terminated", "expired"])], columns: ["employee_id", "plan_id", "membership_number", "eligibility", "status", "effective_date", "expiration_date"] },
  claims: { title: "Claims & reimbursements", singular: "claim", description: "Record the employee's expense, supporting document, requested amount and approved amount. Workflow: Pending → Under Review → Finance Approval → Approved/Rejected → Paid.", roles: [...people, "payroll_manager"],
    fields: [employee, { key: "claim_number", label: "Claim number", required: true }, { key: "category", label: "Claim type", type: "select", options: ["medical", "transportation", "meals", "travel", "communication", "office_expense", "other"], required: true }, date("expense_date", "Expense date"), { key: "description", label: "Description / purpose", type: "textarea", required: true }, money("requested_amount", "Requested amount"), money("approved_amount", "Approved amount"), { key: "receipt_url", label: "Receipt / supporting document URL", help: "HTTPS link to a document you are authorized to review. File uploads require a separate secure storage integration." }, { key: "verification_status", label: "Document review", type: "select", options: ["pending", "verified", "needs_review", "missing_document"], required: true }, status(["draft", "pending", "under_review", "finance_approval", "approved", "rejected", "paid"]), { key: "rejection_reason", label: "Rejection reason", type: "textarea" }], columns: ["claim_number", "employee_id", "category", "expense_date", "requested_amount", "approved_amount", "verification_status", "status", "reviewer_id", "finance_approver_id", "approved_at", "paid_at"] },
  payroll_runs: { title: "Payroll runs", singular: "payroll run", description: "Create a 1st-cutoff, 2nd-cutoff, or monthly draft, then open it to calculate salaries, attendance deductions, statutory deductions, benefits, reimbursements, and payslips.", roles: payroll,
    fields: [{ ...date("period_start", "Period start"), help: "First cutoff starts on the 1st; final cutoff starts on the 16th; monthly starts on the 1st." }, { ...date("period_end", "Period end"), help: "Use the 15th for first cutoff, or the calendar month's last day for final/monthly payroll." }, { ...date("pay_date", "Pay date"), help: "May be the period end or a later date. Payroll preparation is recorded as two days before payday." }], columns: ["schedule", "period_start", "period_end", "preparation_date", "pay_date", "employee_count", "total_gross", "total_deductions", "total_net", "status"] },
  payroll_items: { title: "Employee payroll entries", singular: "payroll entry", description: "Calculated payroll details. Recalculate after changing attendance, salary, approved leave, benefits, or claims; bonus and other authorized deductions remain editable in a draft.", roles: payroll,
    fields: [{ key: "payroll_run_id", label: "Payroll run", reference: "payroll_runs", required: true, createOnly: true }, employee, money("bonus", "Approved bonus"), money("other_deductions", "Other authorized deductions"), status(["needs_review", "ready", "excluded"])], columns: ["employee_id", "salary_frequency", "basic_salary", "paid_leave_days", "late_minutes", "late_deduction", "overtime_minutes", "overtime", "night_differential", "bonus", "sss_employee", "philhealth_employee", "pagibig_employee", "withholding_tax", "deductions", "gross_pay", "net_pay", "status"] },
  payroll_validation_cases: { title: "Payslip comparison cases", singular: "comparison case", description: "Enter totals from anonymized, approved historical payslips. Payroll validation compares the calculated employee entry against these expected amounts before submission.", roles: payroll,
    fields: [{ key: "payroll_run_id", label: "Payroll run", reference: "payroll_runs", required: true }, employee, { key: "source_reference", label: "Source reference", required: true, help: "Use an internal reference only; do not store sensitive document contents." }, money("expected_gross", "Expected gross"), money("expected_deductions", "Expected deductions"), money("expected_net", "Expected net"), { key: "notes", label: "Notes", type: "textarea" }], columns: ["payroll_run_id", "employee_id", "source_reference", "expected_gross", "expected_deductions", "expected_net"] },
};

export type RecordRow = { id: string; updated_at: string; [key: string]: string | number | boolean | null };
export const modules = {
  attendance: ["profiles", "attendance_records", "leave_requests", "departments"],
  compensation: ["compensation_reviews", "compensation_cycles", "employee_compensation_history"],
  benefits: ["employee_benefits", "benefit_plans", "benefit_providers"],
  claims: ["claims"], payroll: ["payroll_runs", "employee_compensation_history", "payroll_validation_cases"],
} as const;

export function recordLabel(entity: string, row: RecordRow) {
  if (entity === "profiles") return `${row.employee_number} · ${row.first_name} ${row.last_name}`;
  if (entity === "payroll_runs") return `${row.period_start} – ${row.period_end} (${row.status})`;
  return String(row.name ?? row.claim_number ?? row.membership_number ?? row.id);
}
