"use client";

import { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import {
  ArrowRight, BadgeCheck, BarChart3, Building2, Calculator, Check, ChevronDown,
  CircleCheck, DatabaseZap, FileSpreadsheet, Fingerprint, HeartPulse,
  Landmark, Menu, Play, ReceiptText, ShieldCheck, Sparkles, UsersRound,
  WalletCards, X, Zap,
} from "lucide-react";
import payrollLogo from "@/Payroll-logo-removebg.png";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const navigation = [["Product", "#product"], ["Solutions", "#solutions"], ["How it works", "#workflow"], ["Security", "#security"], ["FAQ", "#faq"]];
const previewData = {
  Payroll: { value: "₱6.30M", label: "Net payroll", bars: [42, 51, 48, 62, 57, 69, 66, 78, 75, 86, 82, 92] },
  Attendance: { value: "97.6%", label: "Attendance rate", bars: [68, 73, 70, 81, 78, 84, 76, 88, 85, 91, 87, 94] },
  Analytics: { value: "94.7%", label: "Model accuracy", bars: [54, 60, 58, 65, 70, 68, 76, 74, 82, 86, 88, 96] },
};
type PreviewTab = keyof typeof previewData;

const features = [
  { icon: DatabaseZap, title: "One trusted data layer", text: "Synchronize employees, attendance, compensation, approved claims, and benefit requests securely from ESS.", tone: "bg-indigo-50 text-indigo-600" },
  { icon: Calculator, title: "Payroll without guesswork", text: "Calculate salary, overtime, undertime, absences, statutory deductions, and contributions transparently.", tone: "bg-sky-50 text-sky-600" },
  { icon: HeartPulse, title: "Benefits that stay connected", text: "Manage HMO, allowances, insurance, leave, and mandated benefits through payroll application.", tone: "bg-emerald-50 text-emerald-600" },
  { icon: ReceiptText, title: "Claims with a clear trail", text: "Retrieve ESS approvals, verify documents, process reimbursements, and include claims in payroll.", tone: "bg-amber-50 text-amber-600" },
  { icon: BarChart3, title: "Analytics that explain why", text: "Understand workforce cost, attendance patterns, and XGBoost anomaly signals with actionable reports.", tone: "bg-violet-50 text-violet-600" },
  { icon: FileSpreadsheet, title: "Reports people can use", text: "Download operational records or export genuine Excel workbooks from every workspace.", tone: "bg-slate-100 text-slate-600" },
];

const faqs = [
  ["Can it connect to our existing ESS?", "Yes. Secure server-side integrations synchronize employees, attendance, compensation, approved claims, and benefit requests with cursor-based audit history."],
  ["Does it support Philippine payroll?", "Yes. The implemented payroll engine itemizes SSS, PhilHealth, BIR withholding, regular-day overtime, bonuses, late and absence deductions, and approved paid leave. Pag-IBIG, holiday/rest-day premiums, night differential, loans, and 13th-month rules require a future reviewed rule set."],
  ["How is payroll information protected?", "Authorization is enforced in PostgreSQL through Supabase Row Level Security. Employees, managers, HR, and payroll roles receive carefully scoped access."],
  ["Can reports be exported to Excel?", "Yes. Operational record workspaces provide CSV and genuine .xlsx exports. Payroll adds a detailed Excel register and print-ready employee payslips."],
  ["Does AI change payroll automatically?", "No. XGBoost classifications and anomaly scores are review signals. They never modify payroll without an approved, auditable adjustment."],
];

function Brand({ dark = false }: { dark?: boolean }) {
  return (
    <Link href="/" className="flex items-center" aria-label="Payroll and Benefits home">
      <span className={cn("flex h-14 w-[144px] shrink-0 items-center justify-center overflow-hidden sm:h-16 sm:w-[168px]", dark && "rounded-lg bg-white px-2")}>
        <Image src={payrollLogo} alt="Priority Handling Logistics, Inc." priority className="h-full w-full object-contain" sizes="(max-width: 639px) 144px, 168px" />
      </span>
    </Link>
  );
}

function ProductPreview() {
  const [tab, setTab] = useState<PreviewTab>("Payroll");
  const data = previewData[tab];
  return (
    <div className="relative mx-auto w-full max-w-[720px]">
      <div className="absolute -inset-6 -z-10 rounded-[32px] bg-indigo-100/60 blur-3xl" />
      <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_24px_70px_rgba(30,41,59,0.16)]">
        <div className="flex h-11 items-center border-b border-slate-200 bg-slate-50/80 px-4">
          <div className="flex gap-1.5"><span className="size-2.5 rounded-full bg-red-300" /><span className="size-2.5 rounded-full bg-amber-300" /><span className="size-2.5 rounded-full bg-emerald-300" /></div>
          <div className="mx-auto flex items-center gap-1.5 rounded-md border bg-white px-3 py-1 text-[9px] text-slate-400"><ShieldCheck className="size-3 text-emerald-500" />Illustrative product preview</div>
        </div>
        <div className="flex min-h-[370px]">
          <aside className="hidden w-[132px] border-r border-slate-200 bg-slate-50/60 p-3 sm:block">
            <div className="flex items-center gap-2"><span className="grid size-6 place-items-center rounded bg-indigo-600 text-[9px] font-bold text-white">P</span><span className="text-[9px] font-semibold text-slate-800">Payroll</span></div>
            <div className="mt-6 space-y-1.5">{["Overview", "Employees", "Payroll", "Benefits", "Claims", "Analytics"].map((item, index) => <div className={cn("flex h-7 items-center rounded-md px-2 text-[8px]", index === 0 ? "bg-indigo-50 font-medium text-indigo-700" : "text-slate-400")} key={item}><span className={cn("mr-2 size-2 rounded-sm", index === 0 ? "bg-indigo-500" : "bg-slate-200")} />{item}</div>)}</div>
          </aside>
          <div className="min-w-0 flex-1 bg-[#f8f9fb] p-4 sm:p-5">
            <div className="flex items-start justify-between"><div><p className="text-[8px] font-medium text-slate-400">WORKSPACE / OVERVIEW</p><p className="mt-1.5 text-sm font-semibold text-slate-900">Good morning, Andrea</p><p className="mt-1 text-[8px] text-slate-400">Your people operations are running smoothly.</p></div><span className="rounded-md bg-indigo-600 px-2 py-1.5 text-[8px] font-medium text-white">Review payroll</span></div>
            <div className="mt-4 grid grid-cols-2 gap-2 lg:grid-cols-4">{[["Employees", "248"], ["Net payroll", "₱6.3M"], ["Benefits", "₱857K"], ["Approvals", "14"]].map(([label, value]) => <div className="rounded-lg border border-slate-200 bg-white p-2.5" key={label}><p className="text-[7px] text-slate-400">{label}</p><p className="mt-1 text-xs font-semibold text-slate-800">{value}</p></div>)}</div>
            <div className="mt-3 grid gap-3 lg:grid-cols-[1.45fr_0.75fr]">
              <div className="rounded-lg border border-slate-200 bg-white p-3">
                <div className="flex items-center justify-between"><div><p className="text-[9px] font-semibold text-slate-800">Operations performance</p><p className="mt-0.5 text-[7px] text-slate-400">Last 12 months</p></div><div className="flex rounded bg-slate-100 p-0.5">{(Object.keys(previewData) as PreviewTab[]).map((item) => <button onClick={() => setTab(item)} className={cn("rounded px-1.5 py-1 text-[6px]", tab === item ? "bg-white font-medium text-slate-700 shadow-sm" : "text-slate-400")} key={item}>{item}</button>)}</div></div>
                <div className="mt-3 flex items-end justify-between"><div><p className="text-sm font-semibold text-slate-900">{data.value}</p><p className="text-[7px] text-slate-400">{data.label}</p></div><span className="text-[7px] font-medium text-emerald-600">↗ +3.2%</span></div>
                <div key={tab} className="mt-4 flex h-24 items-end gap-1.5 border-b border-slate-100">{data.bars.map((height, index) => <div key={index} className="chart-bar-y-animate min-w-0 flex-1 rounded-t bg-indigo-400" style={{ height: `${height}%`, animationDelay: `${index * 45}ms` }} />)}</div>
              </div>
              <div className="rounded-lg border border-slate-200 bg-white p-3">
                <p className="text-[9px] font-semibold text-slate-800">Payroll readiness</p><p className="mt-0.5 text-[7px] text-slate-400">August 16–31</p>
                <div className="mt-4 grid place-items-center"><div className="grid size-20 place-items-center rounded-full" style={{ background: "conic-gradient(#4f46e5 0 75%, #eef2f7 75% 100%)" }}><div className="grid size-14 place-items-center rounded-full bg-white text-center"><div><p className="text-sm font-semibold text-slate-900">75%</p><p className="text-[6px] text-slate-400">complete</p></div></div></div></div>
                <div className="mt-4 space-y-1.5">{["ESS data synced", "Payroll calculated", "Final approval"].map((item, index) => <div className="flex items-center gap-1.5 text-[7px] text-slate-500" key={item}><span className={cn("grid size-3 place-items-center rounded-full", index < 2 ? "bg-emerald-50 text-emerald-600" : "bg-slate-100")}>{index < 2 && <Check className="size-2" />}</span>{item}</div>)}</div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="absolute -bottom-5 -left-3 hidden items-center gap-3 rounded-xl border border-slate-200 bg-white p-3 shadow-xl md:flex"><span className="grid size-9 place-items-center rounded-lg bg-emerald-50 text-emerald-600"><CircleCheck className="size-4" /></span><div><p className="text-xs font-semibold text-slate-800">Example synchronization state</p><p className="mt-0.5 text-[10px] text-slate-400">Preview data · not a live status</p></div></div>
    </div>
  );
}

function FeatureSection() {
  return <section id="product" className="scroll-mt-20 px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><div className="mx-auto w-full max-w-[1440px]"><div className="mx-auto max-w-2xl text-center"><span className="text-xs font-semibold uppercase tracking-[0.12em] text-indigo-600">A complete operations layer</span><h2 className="mt-4 text-3xl font-semibold tracking-[-0.035em] text-slate-950 sm:text-4xl">Every payroll workflow, working together.</h2><p className="mt-4 text-base leading-7 text-slate-600">Replace disconnected spreadsheets and approval trails with one clear, secure source of truth.</p></div><div className="mt-14 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map((feature) => { const Icon = feature.icon; return <article className="group rounded-2xl border border-slate-200 bg-white p-6 transition duration-300 hover:-translate-y-1 hover:border-indigo-200 hover:shadow-[0_18px_45px_rgba(30,41,59,0.08)]" key={feature.title}><span className={cn("grid size-10 place-items-center rounded-xl", feature.tone)}><Icon className="size-5" /></span><h3 className="mt-5 text-base font-semibold text-slate-900">{feature.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{feature.text}</p><a href="#solutions" className="mt-5 inline-flex items-center gap-1 text-xs font-semibold text-indigo-600 opacity-0 transition group-hover:opacity-100">Learn more<ArrowRight className="size-3.5" /></a></article>; })}</div></div></section>;
}

function SolutionsSection() {
  const health = [{ label: "ESS synchronization", value: "248 records", icon: DatabaseZap, progress: 100 }, { label: "Attendance validation", value: "245 / 248", icon: Fingerprint, progress: 98 }, { label: "Payroll calculation", value: "75% ready", icon: Calculator, progress: 75 }, { label: "Claims verification", value: "4 pending", icon: ReceiptText, progress: 67 }];
  return <section id="solutions" className="scroll-mt-20 bg-slate-950 px-4 py-20 text-white sm:px-6 sm:py-28 lg:px-8"><div className="mx-auto grid w-full max-w-[1440px] items-center gap-14 lg:grid-cols-2"><div><span className="text-xs font-semibold uppercase tracking-[0.12em] text-indigo-300">Built for the whole operating team</span><h2 className="mt-4 max-w-xl text-3xl font-semibold tracking-[-0.035em] sm:text-4xl">HR understands the people. Finance trusts the numbers.</h2><p className="mt-5 max-w-xl text-base leading-7 text-slate-400">Each team gets the context it needs without losing shared controls, history, or accountability.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{[{ title: "HR & People Ops", icon: UsersRound, text: "Employee data, benefits, compensation, and eligibility." }, { title: "Payroll teams", icon: WalletCards, text: "Calculations, adjustments, contributions, and history." }, { title: "Finance leaders", icon: Landmark, text: "Reliable costs, approvals, exports, and auditability." }, { title: "Department managers", icon: Building2, text: "Scoped visibility and actionable team insights." }].map((item) => { const Icon = item.icon; return <div className="rounded-xl border border-white/10 bg-white/[0.04] p-4" key={item.title}><Icon className="size-5 text-indigo-300" /><h3 className="mt-3 text-sm font-semibold">{item.title}</h3><p className="mt-1.5 text-xs leading-5 text-slate-400">{item.text}</p></div>; })}</div></div><div className="rounded-2xl border border-white/10 bg-white/[0.05] p-5"><div className="flex items-center justify-between"><div><p className="text-sm font-semibold">Illustrative workflow</p><p className="mt-1 text-xs text-slate-400">Example values used to demonstrate the interface</p></div><span className="rounded-md bg-indigo-500/10 px-2 py-1 text-[10px] text-indigo-200">Product preview</span></div><div className="mt-6 space-y-3">{health.map((item, index) => { const Icon = item.icon; return <div className="rounded-xl border border-white/10 bg-slate-900/60 p-4" key={item.label}><div className="flex items-center gap-3"><span className="grid size-8 place-items-center rounded-lg bg-white/10 text-indigo-300"><Icon className="size-4" /></span><div className="min-w-0 flex-1"><div className="flex justify-between text-xs"><span>{item.label}</span><span className="text-slate-400">{item.value}</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="chart-bar-x-animate h-full rounded-full bg-indigo-400" style={{ width: `${item.progress}%`, animationDelay: `${index * 100}ms` }} /></div></div></div></div>; })}</div></div></div></section>;
}

export function LandingPage({ isAuthenticated }: { isAuthenticated: boolean }) {
  const [mobileOpen, setMobileOpen] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(0);
  return <div className="min-h-screen overflow-x-hidden bg-white text-slate-900">
    <header className="fixed inset-x-0 top-0 z-50 border-b border-slate-200/80 bg-white/90 backdrop-blur-xl"><div className="relative mx-auto flex h-[76px] w-full max-w-[1440px] items-center px-4 sm:h-[84px] sm:px-6 lg:px-8"><Brand /><nav className="absolute left-1/2 hidden -translate-x-1/2 items-center gap-7 lg:flex">{navigation.map(([label, href]) => <a href={href} className="text-sm font-medium text-slate-500 transition hover:text-slate-950" key={label}>{label}</a>)}</nav><div className="ml-auto hidden items-center gap-2 sm:flex">{isAuthenticated ? <Button asChild><Link href="/overview">Open dashboard<ArrowRight /></Link></Button> : <Button variant="ghost" asChild><Link href="/login">Sign in</Link></Button>}</div><button onClick={() => setMobileOpen((value) => !value)} className="ml-auto grid size-9 place-items-center rounded-lg text-slate-600 hover:bg-slate-100 sm:hidden" aria-label="Toggle navigation">{mobileOpen ? <X className="size-5" /> : <Menu className="size-5" />}</button></div>{mobileOpen && <div className="border-t bg-white px-4 py-4 sm:hidden">{navigation.map(([label, href]) => <a href={href} onClick={() => setMobileOpen(false)} className="block rounded-lg px-3 py-2.5 text-sm font-medium text-slate-600 hover:bg-slate-50" key={label}>{label}</a>)}<Button className="mt-4 w-full" asChild><Link href={isAuthenticated ? "/overview" : "/login"}>{isAuthenticated ? <>Open dashboard<ArrowRight /></> : "Sign in"}</Link></Button></div>}</header>

    <main>
      <section className="relative overflow-hidden px-4 pb-20 pt-32 sm:px-6 sm:pb-28 sm:pt-40 lg:px-8"><div className="pointer-events-none absolute inset-x-0 top-0 -z-10 h-[700px] bg-[radial-gradient(circle_at_50%_0%,rgba(99,102,241,0.14),transparent_58%)]" /><div className="mx-auto grid w-full max-w-[1440px] items-center gap-14 lg:grid-cols-[0.9fr_1.1fr] lg:gap-16"><div className="text-center lg:text-left"><div className="inline-flex items-center gap-2 rounded-full border border-indigo-200 bg-indigo-50 px-3 py-1.5 text-xs font-medium text-indigo-700"><Sparkles className="size-3.5" />Payroll operations, finally connected</div><h1 className="mt-6 text-4xl font-semibold leading-[1.08] tracking-[-0.045em] text-slate-950 sm:text-5xl lg:text-[62px]">Close payroll with clarity, not chaos.</h1><p className="mx-auto mt-6 max-w-xl text-base leading-7 text-slate-600 sm:text-lg sm:leading-8 lg:mx-0">Bring employee data, attendance, compensation, benefits, claims, payroll, and predictive HR analytics into one secure operating system.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row lg:justify-start"><Button className="h-11 px-5" asChild><Link href={isAuthenticated ? "/overview" : "/login"}>{isAuthenticated ? "Open dashboard" : "Sign in to workspace"}<ArrowRight /></Link></Button><Button className="h-11 px-5" variant="secondary" asChild><a href="#product"><Play className="fill-current" />See how it works</a></Button></div><div className="mt-8 flex flex-wrap justify-center gap-x-5 gap-y-2 text-xs text-slate-500 lg:justify-start">{["No billing required", "Philippine payroll workflows", "Database-enforced RBAC"].map((item) => <span className="flex items-center gap-1.5" key={item}><Check className="size-3.5 text-emerald-500" />{item}</span>)}</div></div><ProductPreview /></div></section>
      <section className="border-y border-slate-200 bg-slate-50/60"><div className="mx-auto grid w-full max-w-[1440px] gap-6 px-4 py-8 sm:grid-cols-3 lg:grid-cols-6">{[["3", "payroll schedules"], ["4", "attendance classes"], ["3", "statutory calculations"], ["6", "workspace roles"], ["2", "export formats"], ["1", "audited data layer"]].map(([value, label]) => <div className="text-center" key={label}><p className="text-lg font-semibold">{value}</p><p className="mt-1 text-[11px] text-slate-500">{label}</p></div>)}</div></section>
      <FeatureSection />
      <SolutionsSection />

      <section id="workflow" className="scroll-mt-20 px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><div className="mx-auto w-full max-w-[1440px]"><span className="text-xs font-semibold uppercase tracking-[0.12em] text-indigo-600">From sync to payout</span><h2 className="mt-4 text-3xl font-semibold tracking-[-0.035em] sm:text-4xl">A process everyone can follow.</h2><div className="mt-14 grid gap-8 md:grid-cols-2 lg:grid-cols-4">{[{ title: "Synchronize", text: "Retrieve employee, attendance, salary, benefit, and claim records from ESS.", icon: DatabaseZap }, { title: "Validate", text: "Identify missing documents, time conflicts, eligibility issues, and anomalies.", icon: ShieldCheck }, { title: "Calculate", text: "Compute earnings, adjustments, deductions, contributions, and benefits.", icon: Calculator }, { title: "Approve & pay", text: "Review exceptions, approve payroll, and export final records.", icon: BadgeCheck }].map((step, index) => { const Icon = step.icon; return <div key={step.title}><div className="flex items-center justify-between"><span className="grid size-12 place-items-center rounded-xl bg-indigo-50 text-indigo-600"><Icon className="size-5" /></span><span className="text-xs font-semibold text-slate-300">0{index + 1}</span></div><h3 className="mt-5 text-lg font-semibold">{step.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{step.text}</p></div>; })}</div></div></section>

      <section className="bg-slate-50 px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><div className="mx-auto grid w-full max-w-[1440px] items-center gap-14 lg:grid-cols-[0.8fr_1.2fr]"><div><span className="text-xs font-semibold uppercase tracking-[0.12em] text-indigo-600">Secure integrations</span><h2 className="mt-4 text-3xl font-semibold tracking-[-0.035em] sm:text-4xl">Works with your HR ecosystem.</h2><p className="mt-4 text-base leading-7 text-slate-600">Connect source systems without exposing secrets or relying on browser-side permissions.</p><ul className="mt-6 space-y-3">{["Server-only ESS and model credentials", "Cursor-based synchronization", "Supabase RLS for salary data", "Versioned XGBoost contracts"].map((item) => <li className="flex gap-2 text-sm text-slate-600" key={item}><CircleCheck className="size-4 shrink-0 text-emerald-500" />{item}</li>)}</ul></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{[{ name: "Employee Self-Service", icon: UsersRound }, { name: "Supabase", icon: DatabaseZap }, { name: "PostgreSQL", icon: Landmark }, { name: "XGBoost", icon: Sparkles }, { name: "Excel", icon: FileSpreadsheet }, { name: "Attendance devices", icon: Fingerprint }].map((item) => { const Icon = item.icon; return <div className="flex min-h-28 flex-col items-center justify-center rounded-2xl border bg-white p-4 text-center" key={item.name}><span className="grid size-10 place-items-center rounded-xl bg-slate-50 text-slate-600"><Icon className="size-5" /></span><p className="mt-3 text-xs font-medium">{item.name}</p></div>; })}</div></div></section>

      <section id="security" className="scroll-mt-20 border-y bg-slate-50/70 px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><div className="mx-auto w-full max-w-[1440px]"><div className="mx-auto max-w-2xl text-center"><span className="text-xs font-semibold uppercase tracking-[0.12em] text-indigo-600">Operational safeguards</span><h2 className="mt-4 text-3xl font-semibold tracking-[-0.035em] sm:text-4xl">Controls that follow the payroll workflow.</h2><p className="mt-4 text-sm leading-6 text-slate-500">These are implemented product capabilities, not subscription plans or pricing claims.</p></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{[{title:"Access control",copy:"Active-account checks, protected ownership, role-based modules, department scope, and database RLS.",items:["Six workspace roles","Immediate database denial","Audited access changes"]},{title:"Payroll control",copy:"Calculated drafts move through explicit submission, approval, locking, and payment states.",items:["Cutoff and monthly schedules","Independent approval roles","Immutable finalized entries"]},{title:"Traceable outputs",copy:"Detailed registers and employee payslips expose earnings, attendance minutes, and every deduction.",items:["Excel and CSV exports","Print-ready payslips","Record-level history"]}].map((group)=><article className="rounded-2xl border bg-white p-6" key={group.title}><ShieldCheck className="size-5 text-indigo-600"/><h3 className="mt-5 text-lg font-semibold">{group.title}</h3><p className="mt-2 min-h-16 text-sm leading-6 text-slate-500">{group.copy}</p><ul className="mt-5 space-y-3 border-t pt-5">{group.items.map((item)=><li className="flex gap-2 text-sm text-slate-600" key={item}><Check className="size-4 shrink-0 text-emerald-500"/>{item}</li>)}</ul></article>)}</div></div></section>

      <section id="faq" className="scroll-mt-20 px-4 py-20 sm:px-6 sm:py-28 lg:px-8"><div className="mx-auto grid w-full max-w-[1440px] gap-12 lg:grid-cols-[0.7fr_1.3fr]"><div><span className="text-xs font-semibold uppercase tracking-[0.12em] text-indigo-600">Frequently asked</span><h2 className="mt-4 text-3xl font-semibold tracking-[-0.035em]">Questions, answered clearly.</h2><Button className="mt-6" variant="secondary" asChild><Link href="/overview">Explore dashboard<ArrowRight /></Link></Button></div><div className="divide-y border-y">{faqs.map(([question, answer], index) => <div key={question}><button onClick={() => setOpenFaq(openFaq === index ? null : index)} className="flex w-full items-center justify-between gap-4 py-5 text-left"><span className="font-semibold">{question}</span><ChevronDown className={cn("size-4 transition", openFaq === index && "rotate-180")} /></button>{openFaq === index && <p className="pb-5 text-sm leading-6 text-slate-500">{answer}</p>}</div>)}</div></div></section>

      <section className="px-4 pb-20 sm:px-6 sm:pb-28"><div className="mx-auto w-full max-w-[1440px] rounded-3xl bg-indigo-600 px-6 py-14 text-center text-white"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1.5 text-xs"><Zap className="size-3.5" />Ready when your payroll team is</span><h2 className="mx-auto mt-5 max-w-2xl text-3xl font-semibold tracking-[-0.035em] sm:text-4xl">Make the next payroll your clearest one yet.</h2><p className="mt-4 text-indigo-100">Sign in to work with your organization’s connected records. The interface examples above are illustrative.</p><Button className="mt-7 h-11 bg-white px-5 text-indigo-700 hover:bg-indigo-50" asChild><Link href={isAuthenticated ? "/overview" : "/login"}>{isAuthenticated ? <>Open the dashboard<ArrowRight /></> : <>Sign in to workspace<ArrowRight /></>}</Link></Button></div></section>
    </main>

    <footer className="bg-slate-950 px-4 py-12 text-slate-400 sm:px-6 lg:px-8"><div className="mx-auto w-full max-w-[1440px]"><div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-4"><div><Brand dark /><p className="mt-4 max-w-xs text-xs leading-5">A secure operating system for connected payroll, benefits, employee data, and HR analytics.</p></div>{[{ title: "Product", links: ["Overview", "Payroll", "Benefits", "Analytics"] }, { title: "Solutions", links: ["HR teams", "Payroll teams", "Finance", "Enterprise"] }, { title: "Company", links: ["Security", "Documentation", "Privacy", "Contact"] }].map((group) => <div key={group.title}><p className="text-xs font-semibold text-white">{group.title}</p><ul className="mt-4 space-y-3">{group.links.map((item) => <li key={item}><a href="#product" className="text-xs hover:text-white">{item}</a></li>)}</ul></div>)}</div><div className="mt-10 border-t border-white/10 pt-6 text-[11px]">© 2026 Payroll & Benefits. All rights reserved.</div></div></footer>
  </div>;
}
