"use client";

import { useMemo, useState } from "react";
import Link from "next/link";
import {
  Activity, ArrowRight, ArrowUpRight, BadgeCheck, Banknote, BriefcaseBusiness,
  CalendarDays, Check, ChevronDown, ChevronRight, CircleAlert, FileCheck2,
  Fingerprint, HeartPulse, MoreHorizontal, ReceiptText, RefreshCw, ShieldCheck,
  Sparkles, UserPlus, UsersRound, WalletCards,
} from "lucide-react";
import { toast } from "sonner";
import { DownloadOverviewReport } from "@/components/overview/overview-actions";
import { PayrollStatusBadge } from "@/components/shared/status-badge";
import { Button } from "@/components/ui/button";
import { cn, formatCurrency } from "@/lib/utils";

const trendSeries = {
  net: { label: "Net payroll", values: [5.45, 5.56, 5.62, 5.77, 5.86, 5.94, 6.02, 6.08, 6.12, 6.21, 6.18, 6.3], color: "#4f46e5" },
  gross: { label: "Gross payroll", values: [6.42, 6.55, 6.61, 6.83, 6.94, 7.03, 7.12, 7.19, 7.24, 7.36, 7.32, 7.45], color: "#0ea5e9" },
  benefits: { label: "Benefits cost", values: [0.69, 0.7, 0.72, 0.73, 0.75, 0.77, 0.78, 0.8, 0.81, 0.83, 0.84, 0.857], color: "#10b981" },
};
type TrendMetric = keyof typeof trendSeries;

const departmentFactors: Record<string, number> = { all: 1, engineering: 0.29, sales: 0.21, customer: 0.17, product: 0.15, operations: 0.11, finance: 0.07 };
const rangeMonths: Record<string, number> = { "12m": 12, "6m": 6, "3m": 3 };
const labels = ["Sep", "Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug"];

const departments = [
  { key: "engineering", name: "Engineering", people: 72, percent: 29, cost: 3.72 },
  { key: "sales", name: "Sales", people: 51, percent: 21, cost: 2.81 },
  { key: "customer", name: "Customer Success", people: 43, percent: 17, cost: 1.94 },
  { key: "product", name: "Product & Design", people: 36, percent: 15, cost: 1.82 },
  { key: "operations", name: "Operations", people: 28, percent: 11, cost: 1.31 },
  { key: "finance", name: "Finance & People", people: 18, percent: 7, cost: 1.0 },
];

const activityItems = [
  { type: "payroll", title: "Payroll run submitted for approval", detail: "Andrea Morales · Aug 16–31 payroll", time: "18 min ago", icon: WalletCards, tone: "indigo" },
  { type: "claims", title: "Claim CLM-2026-184 verified", detail: "Medical reimbursement · Mikaela Santos", time: "1 hr ago", icon: ReceiptText, tone: "emerald" },
  { type: "benefits", title: "New employee enrolled in HMO", detail: "Jules Navarro · Maxicare Platinum Plus", time: "3 hrs ago", icon: HeartPulse, tone: "sky" },
  { type: "people", title: "Compensation recommendation submitted", detail: "Product & Design · FY 2026 cycle", time: "Yesterday", icon: BriefcaseBusiness, tone: "amber" },
  { type: "payroll", title: "Attendance adjustments recalculated", detail: "248 records · 3 exceptions detected", time: "Yesterday", icon: Fingerprint, tone: "violet" },
];

const initialTasks = [
  { id: "payroll", title: "Review payroll exceptions", detail: "3 adjustments above threshold", due: "Due today", href: "/payroll-benefits/payroll" as const, icon: WalletCards, color: "bg-amber-50 text-amber-600", done: false },
  { id: "claims", title: "Verify reimbursement claims", detail: "4 claims totaling ₱28,450", due: "Oldest: 2d", href: "/payroll-benefits/claims" as const, icon: ReceiptText, color: "bg-sky-50 text-sky-600", done: false },
  { id: "benefits", title: "Check HMO eligibility", detail: "2 requests need documents", due: "Due Sep 2", href: "/payroll-benefits/benefits" as const, icon: ShieldCheck, color: "bg-emerald-50 text-emerald-600", done: false },
  { id: "attendance", title: "Resolve attendance conflict", detail: "1 ESS time record mismatch", due: "Due today", href: "/payroll-benefits/attendance" as const, icon: Fingerprint, color: "bg-violet-50 text-violet-600", done: false },
];

function Sparkline({ values, color }: { values: number[]; color: string }) {
  const min = Math.min(...values); const max = Math.max(...values);
  const points = values.map((value, index) => `${index * 13},${27 - ((value - min) / Math.max(max - min, 0.01)) * 22}`).join(" ");
  return <svg viewBox="0 0 78 30" className="h-8 w-[78px] overflow-visible" aria-hidden="true"><polyline points={points} fill="none" stroke={color} strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="chart-line-animate" /></svg>;
}

function KpiCard({ label, value, helper, trend, icon: Icon, chart, warning }: { label: string; value: string; helper: string; trend: string; icon: typeof UsersRound; chart: number[]; warning?: boolean }) {
  return <div className="group relative overflow-hidden border-r border-slate-200 p-5 last:border-r-0 transition hover:bg-slate-50/50"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className={cn("grid size-8 place-items-center rounded-lg", warning ? "bg-amber-50 text-amber-600" : "bg-indigo-50 text-indigo-600")}><Icon className="size-4" /></span><p className="text-xs font-medium text-slate-500">{label}</p></div><button className="grid size-7 place-items-center rounded-md text-slate-300 opacity-0 transition hover:bg-white hover:text-slate-600 group-hover:opacity-100" aria-label={`${label} options`}><MoreHorizontal className="size-4" /></button></div><div className="mt-4 flex items-end justify-between gap-3"><div><p className="text-2xl font-semibold tracking-[-0.03em] text-slate-950">{value}</p><div className="mt-1.5 flex items-center gap-1.5 text-xs"><span className={cn("flex items-center font-medium", warning ? "text-amber-600" : "text-emerald-600")}>{!warning && <ArrowUpRight className="size-3" />}{trend}</span><span className="text-slate-500">{helper}</span></div></div><Sparkline values={chart} color={warning ? "#f59e0b" : "#6366f1"} /></div></div>;
}

function PerformanceChart({ metric, range, factor, version }: { metric: TrendMetric; range: string; factor: number; version: number }) {
  const [hovered, setHovered] = useState<number | null>(null);
  const months = rangeMonths[range]; const series = trendSeries[metric];
  const values = series.values.slice(-months).map((value) => value * factor); const visibleLabels = labels.slice(-months);
  const width = 680; const left = 45; const right = 660; const top = 20; const bottom = 200;
  const min = Math.min(...values) * 0.92; const max = Math.max(...values) * 1.05;
  const x = (index: number) => left + index * (right - left) / Math.max(values.length - 1, 1);
  const y = (value: number) => bottom - ((value - min) / (max - min)) * (bottom - top);
  const points = values.map((value, index) => `${x(index)},${y(value)}`).join(" ");
  return <div key={version} className="mt-5 h-[260px] w-full"><svg viewBox={`0 0 ${width} 240`} className="h-full w-full overflow-visible" role="img" aria-label={`${series.label} trend over ${months} months`} onMouseLeave={() => setHovered(null)}>{[top, (top + bottom) / 2, bottom].map((line, index) => <g key={line}><line x1={left} x2={right} y1={line} y2={line} stroke="#e8ebf0" strokeDasharray="3 4" /><text x="0" y={line + 4} fill="#94a3b8" fontSize="10">₱{[max, (max + min) / 2, min][index].toFixed(metric === "benefits" ? 1 : 0)}M</text></g>)}<path d={`M ${points.replaceAll(" ", " L ")} L ${right},${bottom} L ${left},${bottom} Z`} fill={series.color} fillOpacity="0.06" className="chart-area-animate" /><polyline points={points} fill="none" stroke={series.color} strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" className="chart-line-animate" vectorEffect="non-scaling-stroke" />{values.map((value, index) => <g key={visibleLabels[index]} onMouseEnter={() => setHovered(index)} className="cursor-pointer"><circle cx={x(index)} cy={y(value)} r="12" fill="transparent" /><circle cx={x(index)} cy={y(value)} r={hovered === index ? 5 : 3.5} fill="white" stroke={series.color} strokeWidth="2" className="chart-point-animate transition-all" style={{ animationDelay: `${450 + index * 50}ms` }} />{hovered === index && <g><line x1={x(index)} x2={x(index)} y1={top} y2={bottom} stroke={series.color} strokeOpacity="0.25" strokeDasharray="3 3" /><rect x={Math.min(right - 94, Math.max(left, x(index) - 47))} y={Math.max(2, y(value) - 48)} width="94" height="34" rx="7" fill="#172033" /><text x={Math.min(right - 47, Math.max(left + 47, x(index)))} y={Math.max(21, y(value) - 28)} fill="white" fontSize="10" textAnchor="middle">{visibleLabels[index]} · ₱{value.toFixed(2)}M</text></g>}<text x={x(index)} y="226" textAnchor="middle" fill="#94a3b8" fontSize="10">{visibleLabels[index]}</text></g>)}</svg><table className="sr-only"><caption>{series.label} trend</caption><tbody>{values.map((value, index) => <tr key={visibleLabels[index]}><th>{visibleLabels[index]}</th><td>{value.toFixed(2)} million pesos</td></tr>)}</tbody></table></div>;
}

export function OverviewDashboard() {
  const [range, setRange] = useState("12m"); const [department, setDepartment] = useState("all");
  const [metric, setMetric] = useState<TrendMetric>("net"); const [activityTab, setActivityTab] = useState("all");
  const [tasks, setTasks] = useState(initialTasks); const [chartVersion, setChartVersion] = useState(0); const [refreshing, setRefreshing] = useState(false);
  const factor = departmentFactors[department]; const employeeCount = department === "all" ? 248 : departments.find((item) => item.key === department)?.people ?? 0;
  const openTasks = tasks.filter((task) => !task.done).length;
  const activities = useMemo(() => activityItems.filter((item) => activityTab === "all" || item.type === activityTab), [activityTab]);
  function updateFilter(setter: (value: string) => void, value: string) { setter(value); setChartVersion((current) => current + 1); }
  function refresh() { setRefreshing(true); setChartVersion((current) => current + 1); window.setTimeout(() => setRefreshing(false), 650); toast.success("Dashboard refreshed", { description: "All operational metrics are up to date." }); }
  function toggleTask(id: string) { setTasks((current) => current.map((task) => task.id === id ? { ...task, done: !task.done } : task)); }

  return <div>
    <div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-start"><div><div className="flex items-center gap-2"><span className="flex items-center gap-1.5 rounded-md bg-emerald-50 px-2 py-1 text-[10px] font-semibold uppercase tracking-wide text-emerald-700"><span className="size-1.5 rounded-full bg-emerald-500" />Live workspace</span><span className="text-xs text-slate-400">Last synced 2 min ago</span></div><div className="mt-3 flex items-center gap-2.5"><h1 className="text-2xl font-semibold tracking-[-0.035em] text-slate-950 sm:text-[30px]">People operations overview</h1><Sparkles className="size-5 text-amber-500" /></div><p className="mt-1.5 max-w-2xl text-sm leading-6 text-slate-500">Monitor workforce health, payroll readiness, costs, and approvals from one operational command center.</p></div><div className="flex flex-wrap items-center gap-2"><DownloadOverviewReport /><Button variant="secondary" onClick={refresh} disabled={refreshing}><RefreshCw className={refreshing ? "animate-spin" : ""} />{refreshing ? "Refreshing…" : "Refresh"}</Button><Button asChild><Link href="/payroll-benefits/payroll">Review payroll<ArrowRight /></Link></Button></div></div>

    <section aria-label="Dashboard filters" className="mt-6 flex flex-wrap items-center gap-2 rounded-xl border border-slate-200 bg-white p-3 shadow-[0_1px_2px_rgba(16,24,40,0.03)]"><span className="mr-1 hidden items-center gap-2 px-1 text-xs font-medium text-slate-500 sm:flex"><CalendarDays className="size-4" />Viewing</span><div className="relative"><select value={range} onChange={(event) => updateFilter(setRange, event.target.value)} className="h-9 appearance-none rounded-lg border border-slate-200 bg-white pl-3 pr-8 text-sm font-medium text-slate-700"><option value="12m">Last 12 months</option><option value="6m">Last 6 months</option><option value="3m">Last 3 months</option></select><ChevronDown className="pointer-events-none absolute right-2.5 top-1/2 size-3.5 -translate-y-1/2 text-slate-400" /></div><div className="relative"><select value={department} onChange={(event) => updateFilter(setDepartment, event.target.value)} className="h-9 appearance-none rounded-lg border border-slate-200 bg-white pl-3 pr-8 text-sm font-medium text-slate-700"><option value="all">All departments</option>{departments.map((item) => <option key={item.key} value={item.key}>{item.name}</option>)}</select><ChevronDown className="pointer-events-none absolute right-2.5 top-1/2 size-3.5 -translate-y-1/2 text-slate-400" /></div><div className="ml-auto flex items-center gap-1.5 rounded-lg bg-slate-50 px-3 py-2 text-xs text-slate-500"><UsersRound className="size-3.5" /><span className="font-medium text-slate-700">{employeeCount}</span> employees in scope</div></section>

    <section aria-label="Organization summary" className="mt-5 grid overflow-hidden rounded-xl border border-slate-200 bg-white shadow-[0_1px_2px_rgba(16,24,40,0.03)] sm:grid-cols-2 xl:grid-cols-4"><KpiCard label="Active employees" value={String(employeeCount)} helper="vs. prior period" trend="+1.6%" icon={UsersRound} chart={[222, 227, 230, 233, 241, 248].map((value) => value * factor)} /><KpiCard label="Current net payroll" value={`₱${(6.3 * factor).toFixed(2)}M`} helper="Aug 16–31" trend="+3.2%" icon={WalletCards} chart={trendSeries.net.values.slice(-6).map((value) => value * factor)} /><KpiCard label="Monthly benefits" value={`₱${(0.857 * factor).toFixed(2)}M`} helper="per month" trend="+0.8%" icon={HeartPulse} chart={trendSeries.benefits.values.slice(-6).map((value) => value * factor)} /><KpiCard label="Open action items" value={String(openTasks)} helper="assigned to you" trend={`${tasks.filter((task) => task.done).length} resolved`} icon={FileCheck2} chart={[7, 8, 6, 6, 5, openTasks]} warning /></section>

    <div className="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1.45fr)_minmax(340px,0.7fr)]"><section className="rounded-xl border border-slate-200 bg-white p-5 shadow-[0_1px_2px_rgba(16,24,40,0.03)]"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-sm font-semibold text-slate-900">People cost performance</h2><p className="mt-1 text-xs text-slate-500">Interactive monthly trend for the selected workforce</p></div><div className="flex rounded-lg bg-slate-100 p-1">{(Object.keys(trendSeries) as TrendMetric[]).map((key) => <button key={key} onClick={() => { setMetric(key); setChartVersion((current) => current + 1); }} className={cn("rounded-md px-2.5 py-1.5 text-xs font-medium transition", metric === key ? "bg-white text-slate-900 shadow-sm" : "text-slate-500 hover:text-slate-700")}>{trendSeries[key].label}</button>)}</div></div><div className="mt-5 flex items-end justify-between"><div><p className="text-2xl font-semibold tracking-tight text-slate-950">₱{(trendSeries[metric].values.at(-1)! * factor).toFixed(2)}M</p><p className="mt-1 text-xs text-slate-500">Current selected period</p></div><span className="flex items-center gap-1 text-xs font-medium text-emerald-600"><ArrowUpRight className="size-3.5" />15.6% year over year</span></div><PerformanceChart metric={metric} range={range} factor={factor} version={chartVersion} /></section>

      <section className="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-[0_1px_2px_rgba(16,24,40,0.03)]"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="text-sm font-semibold text-slate-900">Payroll readiness</h2><p className="mt-1 text-xs text-slate-500">August 16–31, 2026</p></div><PayrollStatusBadge status="pending_approval" /></div><div className="p-5"><div className="flex items-end justify-between"><div><p className="text-xs text-slate-500">Scheduled payment</p><p className="mt-1 text-lg font-semibold text-slate-950">September 5</p></div><div className="text-right"><p className="text-xs text-slate-500">Net payroll</p><p className="mt-1 text-sm font-semibold text-slate-900">{formatCurrency(6302020 * factor)}</p></div></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="chart-bar-x-animate h-full w-3/4 rounded-full bg-indigo-500" /></div><div className="mt-2 flex justify-between text-[10px] text-slate-400"><span>75% complete</span><span>3 exceptions remain</span></div><div className="mt-5 space-y-3">{[{ label: "ESS data synchronized", complete: true, icon: Fingerprint }, { label: "Payroll calculated", complete: true, icon: Banknote }, { label: "Exceptions reviewed", complete: false, icon: CircleAlert }, { label: "Final approval", complete: false, icon: BadgeCheck }].map((step) => { const Icon = step.icon; return <div className="flex items-center gap-3" key={step.label}><span className={cn("grid size-7 place-items-center rounded-full", step.complete ? "bg-emerald-50 text-emerald-600" : "bg-slate-100 text-slate-400")}>{step.complete ? <Check className="size-3.5" /> : <Icon className="size-3.5" />}</span><span className={cn("text-sm", step.complete ? "text-slate-500" : "font-medium text-slate-800")}>{step.label}</span>{step.complete && <span className="ml-auto text-[10px] text-emerald-600">Complete</span>}</div>; })}</div><Button className="mt-5 w-full" asChild><Link href="/payroll-benefits/payroll/8d3de8ce-6131-4c95-9c6e-911167601831">Continue payroll review<ArrowRight /></Link></Button></div></section></div>

    <section className="mt-6 overflow-hidden rounded-xl border border-slate-200 bg-white shadow-[0_1px_2px_rgba(16,24,40,0.03)]"><div className="flex flex-wrap items-center justify-between gap-3 border-b px-5 py-4"><div><h2 className="text-sm font-semibold text-slate-900">Payroll operations pipeline</h2><p className="mt-1 text-xs text-slate-500">Live record flow from ESS synchronization through payment</p></div><span className="flex items-center gap-1.5 text-xs text-emerald-600"><Activity className="size-3.5" />All systems operational</span></div><div className="grid gap-px bg-slate-200 md:grid-cols-5">{[{ label: "ESS synchronized", value: "248", helper: "employee records", icon: Fingerprint, href: "/payroll-benefits/attendance" as const, complete: true }, { label: "Validated", value: "245", helper: "3 exceptions", icon: ShieldCheck, href: "/payroll-benefits/attendance" as const, complete: true }, { label: "Calculated", value: "248", helper: "payroll items", icon: Banknote, href: "/payroll-benefits/payroll" as const, complete: true }, { label: "Approved", value: "0", helper: "awaiting sign-off", icon: FileCheck2, href: "/payroll-benefits/payroll" as const, complete: false }, { label: "Scheduled", value: "Sep 5", helper: "payment date", icon: CalendarDays, href: "/payroll-benefits/payroll" as const, complete: false }].map((stage, index) => { const Icon = stage.icon; return <Link href={stage.href} key={stage.label} className="group relative bg-white p-5 transition hover:bg-slate-50">{index < 4 && <ChevronRight className="absolute -right-2.5 top-1/2 z-10 size-5 -translate-y-1/2 rounded-full border bg-white p-1 text-slate-300" />}<div className="flex items-center justify-between"><span className={cn("grid size-8 place-items-center rounded-lg", stage.complete ? "bg-emerald-50 text-emerald-600" : "bg-slate-100 text-slate-500")}><Icon className="size-4" /></span>{stage.complete && <Check className="size-3.5 text-emerald-500" />}</div><p className="mt-4 text-lg font-semibold text-slate-900">{stage.value}</p><p className="mt-1 text-xs font-medium text-slate-700">{stage.label}</p><p className="mt-0.5 text-[11px] text-slate-400">{stage.helper}</p></Link>; })}</div></section>

    <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-xl border border-slate-200 bg-white shadow-[0_1px_2px_rgba(16,24,40,0.03)]"><div className="flex items-center justify-between border-b px-5 py-4"><div><h2 className="text-sm font-semibold text-slate-900">Action center</h2><p className="mt-1 text-xs text-slate-500">Work assigned to you across the workspace</p></div><span className="rounded-md bg-amber-50 px-2 py-1 text-xs font-medium text-amber-700">{openTasks} open</span></div><div className="divide-y divide-slate-100">{tasks.map((task) => { const Icon = task.icon; return <div className={cn("flex items-center gap-3 px-5 py-4 transition", task.done && "bg-slate-50/70")} key={task.id}><button onClick={() => toggleTask(task.id)} className={cn("grid size-5 shrink-0 place-items-center rounded border transition", task.done ? "border-emerald-500 bg-emerald-500 text-white" : "border-slate-300 bg-white hover:border-indigo-400")} aria-label={task.done ? `Reopen ${task.title}` : `Complete ${task.title}`}>{task.done && <Check className="size-3" />}</button><span className={cn("grid size-9 shrink-0 place-items-center rounded-lg", task.color)}><Icon className="size-4" /></span><div className="min-w-0 flex-1"><p className={cn("truncate text-sm font-medium text-slate-800", task.done && "text-slate-400 line-through")}>{task.title}</p><p className="mt-0.5 truncate text-xs text-slate-500">{task.detail}</p></div><span className="hidden shrink-0 text-xs font-medium text-slate-500 sm:block">{task.due}</span><Link href={task.href} className="grid size-8 place-items-center rounded-lg text-slate-300 hover:bg-slate-100 hover:text-slate-700" aria-label={`Open ${task.title}`}><ChevronRight className="size-4" /></Link></div>; })}</div></section>

      <section className="rounded-xl border border-slate-200 bg-white p-5 shadow-[0_1px_2px_rgba(16,24,40,0.03)]"><div className="flex items-start justify-between"><div><h2 className="text-sm font-semibold text-slate-900">Workforce distribution</h2><p className="mt-1 text-xs text-slate-500">Headcount and monthly cost by department</p></div><Link href="/payroll-benefits/analytics" className="flex items-center gap-1 text-xs font-medium text-indigo-600 hover:text-indigo-700">View analytics<ArrowRight className="size-3.5" /></Link></div><div className="mt-5 space-y-4">{departments.map((item, index) => <button key={item.key} onClick={() => updateFilter(setDepartment, item.key)} className="block w-full text-left"><div className="mb-1.5 flex items-center justify-between text-xs"><span className="font-medium text-slate-700">{item.name}</span><span className="tabular-nums text-slate-500">{item.people} <span className="text-slate-400">· ₱{item.cost.toFixed(2)}M</span></span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={cn("chart-bar-x-animate h-full rounded-full", department === item.key ? "bg-indigo-600" : "bg-indigo-400")} style={{ width: `${item.percent * 3.15}%`, animationDelay: `${index * 60}ms` }} /></div></button>)}</div></section></div>

    <div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1.5fr)_minmax(300px,0.7fr)]"><section className="rounded-xl border border-slate-200 bg-white shadow-[0_1px_2px_rgba(16,24,40,0.03)]"><div className="flex flex-wrap items-center justify-between gap-3 border-b px-5 py-4"><div><h2 className="text-sm font-semibold text-slate-900">Workspace activity</h2><p className="mt-1 text-xs text-slate-500">Recent operational changes</p></div><div className="flex rounded-lg bg-slate-100 p-1">{["all", "payroll", "claims", "benefits"].map((tab) => <button key={tab} onClick={() => setActivityTab(tab)} className={cn("rounded-md px-2.5 py-1 text-[11px] font-medium capitalize transition", activityTab === tab ? "bg-white text-slate-800 shadow-sm" : "text-slate-500")}>{tab}</button>)}</div></div><div className="divide-y divide-slate-100">{activities.map((item) => { const Icon = item.icon; const tones: Record<string, string> = { indigo: "bg-indigo-50 text-indigo-600", emerald: "bg-emerald-50 text-emerald-600", sky: "bg-sky-50 text-sky-600", amber: "bg-amber-50 text-amber-600", violet: "bg-violet-50 text-violet-600" }; return <div className="flex items-center gap-3 px-5 py-3.5" key={item.title}><span className={cn("grid size-8 shrink-0 place-items-center rounded-lg", tones[item.tone])}><Icon className="size-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-slate-800">{item.title}</p><p className="mt-0.5 truncate text-xs text-slate-500">{item.detail}</p></div><time className="shrink-0 text-xs text-slate-400">{item.time}</time></div>; })}{!activities.length && <div className="p-10 text-center text-sm text-slate-500">No activity in this category.</div>}</div></section>

      <section className="rounded-xl border border-slate-200 bg-white shadow-[0_1px_2px_rgba(16,24,40,0.03)]"><div className="border-b px-5 py-4"><h2 className="text-sm font-semibold text-slate-900">Upcoming</h2><p className="mt-1 text-xs text-slate-500">Key dates in the next 14 days</p></div><div className="p-5">{[{ month: "SEP", day: "05", title: "Payroll payment", detail: "248 employees", icon: Banknote }, { month: "SEP", day: "08", title: "3 employee birthdays", detail: "View celebrations", icon: UserPlus }, { month: "SEP", day: "12", title: "Next payroll cutoff", detail: "September 1–15", icon: CalendarDays }].map((event) => { const Icon = event.icon; return <div className="flex gap-3 pb-5 last:pb-0" key={event.title}><div className="w-10 shrink-0 rounded-lg border border-slate-200 bg-slate-50 py-1 text-center"><p className="text-[9px] font-semibold tracking-wide text-indigo-600">{event.month}</p><p className="text-sm font-semibold text-slate-900">{event.day}</p></div><div className="min-w-0 pt-0.5"><p className="flex items-center gap-1.5 text-sm font-medium text-slate-800"><Icon className="size-3.5 text-slate-400" />{event.title}</p><p className="mt-1 text-xs text-slate-500">{event.detail}</p></div></div>; })}</div></section></div>
  </div>;
}
